import { CountryCode, Manager, StoreType } from './types';

export const STORE_TYPES: StoreType[] = [
    { emoji: '🛒', label: 'Retail', suggestedLogos: ['🛒', '🏪', '🏬'] },
    { emoji: '☕', label: 'Cafe', suggestedLogos: ['☕', '🍵', '🥤'] },
    { emoji: '🍞', label: 'Bakery', suggestedLogos: ['🍞', '🥐', '🧁'] },
    { emoji: '🥦', label: 'Grocery', suggestedLogos: ['🥦', '🍎', '🥕'] },
    { emoji: '🏬', label: 'Boutique', suggestedLogos: ['🏬', '👗', '👔'] },
    { emoji: '🧾', label: 'Kiosk', suggestedLogos: ['🧾', '🏪', '📰'] },
    { emoji: '🍕', label: 'Pizza', suggestedLogos: ['🍕', '🍴', '🧑‍🍳'] },
    { emoji: '🍔', label: 'Burger', suggestedLogos: ['🍔', '🍟', '🥤'] },
    { emoji: '🍣', label: 'Sushi', suggestedLogos: ['🍣', '🍱', '🥢'] },
    { emoji: '🥗', label: 'Salad Bar', suggestedLogos: ['🥗', '🥦', '🥕'] },
    { emoji: '🍦', label: 'Ice Cream', suggestedLogos: ['🍦', '🍧', '🍨'] },
    { emoji: '🍰', label: 'Desserts', suggestedLogos: ['🍰', '🧁', '🎂'] },
    { emoji: '🍺', label: 'Bar', suggestedLogos: ['🍺', '🍻', '🍷'] },
    { emoji: '📚', label: 'Bookstore', suggestedLogos: ['📚', '📖', '✏️'] },
    { emoji: '💄', label: 'Cosmetics', suggestedLogos: ['💄', '💅', '💋'] },
    { emoji: '👕', label: 'Clothing', suggestedLogos: ['👕', '👔', '👗'] },
    { emoji: '👟', label: 'Footwear', suggestedLogos: ['👟', '👠', '👞'] },
    { emoji: '💎', label: 'Jewelry', suggestedLogos: ['💎', '💍', '👑'] },
    { emoji: '📱', label: 'Electronics', suggestedLogos: ['📱', '💻', '🖥️'] },
    { emoji: '🎮', label: 'Gaming', suggestedLogos: ['🎮', '🕹️', '👾'] },
    { emoji: '⚽', label: 'Sports', suggestedLogos: ['⚽', '🏀', '⚾'] },
    { emoji: '🐕', label: 'Pet Shop', suggestedLogos: ['🐕', '🐈', '🐾'] },
    { emoji: '🌸', label: 'Florist', suggestedLogos: ['🌸', '🌹', '💐'] },
    { emoji: '🧸', label: 'Toys', suggestedLogos: ['🧸', '🎯', '🪀'] },
];

export const ALL_EMOJIS = [
    '🏪',
    '🏬',
    '🛍️',
    '🛒',
    '☕',
    '🍎',
    '🍞',
    '🧾',
    '🧸',
    '🍕',
    '🍔',
    '🍟',
    '🌮',
    '🌯',
    '🥗',
    '🍱',
    '🍜',
    '🍝',
    '🍣',
    '🍤',
    '🥟',
    '🍦',
    '🍧',
    '🎂',
    '🍰',
    '🧁',
    '🍪',
    '🥐',
    '🥨',
    '🥯',
    '🥖',
    '🧀',
    '🥚',
    '🍳',
    '🥓',
    '🥩',
    '🍗',
    '🍖',
    '🌭',
    '🥪',
    '🥙',
    '🧆',
    '🥘',
    '🥦',
    '🥕',
    '🌽',
    '🌶️',
    '🫑',
    '🥒',
    '🥬',
    '🥑',
    '🍅',
    '🍆',
    '🥔',
    '🍠',
    '🌰',
    '🥜',
    '🍄',
    '🧄',
    '🧅',
    '🍇',
    '🍈',
    '🍉',
    '🍊',
    '🍋',
    '🍌',
    '🍍',
    '🥭',
    '🍑',
    '🍒',
    '🍓',
    '🫐',
    '🥝',
    '🍏',
    '🥥',
    '👕',
    '👔',
    '👗',
    '👘',
    '👜',
    '👝',
    '🎒',
    '👞',
    '👟',
    '🥾',
    '🥿',
    '👠',
    '👡',
    '👢',
    '👑',
    '👒',
    '🎩',
    '💄',
    '💍',
    '💎',
    '📱',
    '💻',
];

export const CURRENCIES = ['KES', 'USD', 'EUR', 'GBP', 'TZS', 'UGX'];

export const TIMEZONES = [
    'Africa/Nairobi',
    'Africa/Lagos',
    'Europe/London',
    'UTC',
    'America/New_York',
];

export const COUNTRY_CODES: CountryCode[] = [
    { code: '+254', label: 'KE', flag: '🇰🇪' },
    { code: '+1', label: 'US', flag: '🇺🇸' },
    { code: '+44', label: 'UK', flag: '🇬🇧' },
    { code: '+255', label: 'TZ', flag: '🇹🇿' },
    { code: '+256', label: 'UG', flag: '🇺🇬' },
];

export const MANAGERS: Manager[] = [
    { id: 'MGR001', name: 'John Doe', avatar: '👨' },
    { id: 'MGR002', name: 'Jane Smith', avatar: '👩' },
    { id: 'MGR003', name: 'Mike Johnson', avatar: '👨‍💼' },
    { id: 'MGR004', name: 'Sarah Williams', avatar: '👩‍💼' },
    { id: 'MGR005', name: 'David Brown', avatar: '🧑' },
];
